name: Label Reviews
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
jobs:
  require-reviewers:
    # Don't skip this job as it's meant to be run for every PR, regardless of its labels
    runs-on: ubuntu-latest
    steps:
      # This workflow uses the current version of the action, so requires a checkout to make it run
      - name: Checkout current version of action
        uses: actions/checkout@v2
      - name: Run action on current PR
        uses: ./       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rules_yaml: |
            typescript: 2
            migration: 5